FROM cosi_grb_bgo_base:test 

USER cosi

RUN cd /home/cosi && python3 -m venv bct

RUN cd /home/cosi \
      && git clone https://gitlab.com/burstcube/bc-tools.git \
      && . bct/bin/activate  \
      && cd bc-tools && git checkout develop && pip install . && cd ..\
      && wget https://fermi.gsfc.nasa.gov/ssc/data/analysis/gbm/gbm_data_tools/gbm_data_tools-1.1.1.tar.gz  \
      && python3 -m pip install  basemap ipykernel "matplotlib>=3.7.1" \
      && pip3 install ./gbm_data_tools-1.1.1.tar.gz \
      && python -m ipykernel install --user --name=bct \
      && sed -i 's/trapz/trapezoid/g' bct/lib/python3.10/site-packages/gdt/core/data_primitives.py 


RUN cd /home/cosi && python3 -m venv deeplearning

RUN cd /home/cosi \
    . deeplearning/bin/activate  \
    && python3 -m pip install tensorflow[and-cuda]==2.19.0 keras matplotlib scipy plotly mhealpy pandas astropy scikit-learn seaborn ipykernel  \
    && python3 -m ipykernel install --user --name=deeplearning 

RUN cd /home/cosi && python3 -m venv cosipy

RUN cd /home/cosi \
    . cosipy/bin/activate  \
    && python3 -m pip install packaging \
    && python3 -m pip install --use-pep517 cosipy \
    && python3 -m pip install ipykernel \
    && python3 -m ipykernel install --user --name=cosipy


RUN pip3 install --user pytest-cov

RUN pip3 install --user sphinx sphinx_rtd_theme

RUN pip3 install --user mhealpy

#To build tutorials
RUN pip3 install --user nbsphinx jupyter_client ipykernel
#ADD --chown=user:user https://github.com/jgm/pandoc/releases/download/2.9.2.1/pandoc-2.9.2.1-linux-amd64.tar.gz $HOME
RUN cd $HOME && wget https://github.com/jgm/pandoc/releases/download/2.9.2.1/pandoc-2.9.2.1-linux-amd64.tar.gz
RUN tar xvzf $HOME/pandoc-2.9.2.1-linux-amd64.tar.gz --strip-components 1 -C $HOME/.local

# For full instrument response
RUN pip3 install --user h5py

#RUN cd /home/cosi && git clone https://github.com/cositools/grb-simulations.git


# Switch back to ROOT
USER root

# For full instrument response
RUN pip3 install notebook pandas

# Create entry-point script - changes the UID of cosi to the local USER and group for full access to the exchange directory on all machines
RUN    cd /usr/local/bin \
    && echo '#!/bin/bash' >> entrypoint.sh \
    && echo 'if [ "${USERID}" != "" ]; then usermod -u ${USERID} cosi; fi' >> entrypoint.sh \
    && echo 'if [ "${GROUPID}" != "" ]; then groupmod -g ${GROUPID} cosi; fi' >> entrypoint.sh \
    && echo 'if [ "${USERID}" != "" ] || [ "${GROUPID}" != "" ]; then chown -R cosi:cosi /home/cosi; fi' >> entrypoint.sh \
    && echo ". /home/cosi/megalib/bin/source-megalib.sh" >> entrypoint.sh \
    && echo 'gosu cosi tail -f /dev/null' >> entrypoint.sh \
    && chmod a+rx /usr/local/bin/entrypoint.sh

# The working directory is the COSItools directory
WORKDIR /home/cosi

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]