# Dockerfile for COSItools
# 
# Build the docker with:
# docker build -t cosi-main - < Dockerfile

FROM ubuntu:22.04

MAINTAINER Andreas Zoglauer <zoglauer@berkeley.edu>

# Install all the COSItools prerequisites
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -yq gosu vim nano less gzip git git-lfs gawk dpkg-dev make g++ gcc gfortran gdb valgrind binutils libx11-dev libxpm-dev libxft-dev libxext-dev libssl-dev libpcre3-dev libglu1-mesa-dev libglew-dev libftgl-dev libmysqlclient-dev libfftw3-dev libgraphviz-dev libavahi-compat-libdnssd-dev libldap2-dev python3 python3-pip python3-dev python3-tk python3-venv libxml2-dev libkrb5-dev libgsl-dev cmake libxmu-dev curl doxygen libblas-dev liblapack-dev expect dos2unix libncurses5-dev libboost-all-dev libcfitsio-dev mlocate libxerces-c-dev libhealpix-cxx-dev libbz2-dev wget

# Add COSI user
RUN groupadd -g 1111 cosi && useradd -u 1111 -g 1111 -ms /bin/bash cosi
#RUN ln -s /usr/bin/python3 /usr/bin/python

# Switch to user cosi
USER cosi

# Setup 
#RUN cd /home/cosi && /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/cositools/cosi-setup/main/setup.sh)"
RUN echo . /home/cosi/COSItools/source.sh >> /home/cosi/.bashrc
#switch megalib branch
# === MEGAlib ===

# Needs a lot of memory. Check your docker preferences if it fails

RUN cd /home/cosi/ && git clone https://github.com/zoglauer/megalib && cd megalib && git checkout develop-cosi

#COPY build-root.sh $MEGALIBDIR/config/build-root.sh

RUN cd /home/cosi/megalib && \
     bash config/configure_packages && \
    bash setup.sh --branch=develop-cosi && \
    echo . /home/cosi/megalib/bin/source-megalib.sh >> $HOME/.bashrc

#ENV PATH="/root/.local/bin:${PATH}"

WORKDIR /home/cosi

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
